[build]
target = "arduboy.json"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
